// src/utils/storeRequestEmail.ts
import PDFDocument from 'pdfkit';
import { PassThrough } from 'stream';
import type { StoreRequest } from '../features/inventory/inventory.types';
import { sendMail } from './sendMail'; // adjust to your actual path
import type { User } from '../features/users/users.types';

/**
 * Generate a PDF buffer for a store request receipt
 */
export const generateStoreRequestPDF = async (
  request: StoreRequest,
  requester: User,
  issuer: User
): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const stream = new PassThrough();
      const chunks: Buffer[] = [];

      stream.on('data', (chunk) => chunks.push(chunk));
      stream.on('end', () => resolve(Buffer.concat(chunks)));
      stream.on('error', reject);

      doc.pipe(stream);

      // ── Header ──
      doc.fontSize(18).font('Helvetica-Bold').text('Store Issue Receipt', { align: 'center' });
      doc.moveDown();
      doc.fontSize(10).font('Helvetica').text(`Date: ${new Date(request.issued_at || new Date()).toLocaleString()}`, { align: 'right' });
      doc.moveDown(0.5);
      doc.text(`Receipt #: ${request.id.slice(0, 8)}`, { align: 'right' });
      doc.moveDown(1.5);

      // ── Requester & Issuer ──
      doc.fontSize(12).font('Helvetica-Bold').text('Issued To:');
      doc.fontSize(11).font('Helvetica').text(`Name: ${requester.full_name}`);
      doc.text(`Email: ${requester.email}`);
      // Use department_id if available; if you have a department name, fetch it.
      doc.text(`Department: ${requester.department_id || 'N/A'}`);
      doc.moveDown(0.5);
      doc.fontSize(12).font('Helvetica-Bold').text('Issued By:');
      doc.fontSize(11).font('Helvetica').text(`Name: ${issuer.full_name}`);
      doc.text(`Email: ${issuer.email}`);
      doc.moveDown(1);

      // ── Item Details ──
      doc.fontSize(12).font('Helvetica-Bold').text('Item Details:');
      doc.moveDown(0.3);
      const tableTop = doc.y;
      const col1 = 50;
      const col2 = 150;
      const col3 = 250;

      // Headers
      doc.fontSize(10).font('Helvetica-Bold');
      doc.text('Item', col1, tableTop);
      doc.text('Quantity', col2, tableTop);
      doc.text('Unit', col3, tableTop);
      doc.moveDown(0.3);

      // Draw line
      doc
        .moveTo(col1, doc.y)
        .lineTo(500, doc.y)
        .stroke();

      doc.fontSize(10).font('Helvetica');
      doc.text(request.item_name, col1, doc.y);
      doc.text(request.quantity.toString(), col2, doc.y);
      doc.text(request.unit, col3, doc.y);

      doc.moveDown(1.5);

      // ── Reason ──
      doc.fontSize(11).font('Helvetica-Bold').text('Reason for Request:');
      doc.fontSize(10).font('Helvetica').text(request.reason || 'Not specified', {
        width: 450,
        align: 'left',
      });
      doc.moveDown(1);

      // ── Status ──
      doc.fontSize(11).font('Helvetica-Bold').text('Status:');
      doc.fillColor('green').fontSize(10).font('Helvetica').text(request.status);
      doc.moveDown(0.5);
      doc.fillColor('black').text(`Received on: ${new Date(request.received_at || new Date()).toLocaleString()}`);
      doc.moveDown(1);

      // ── Footer ──
      doc
        .fontSize(8)
        .font('Helvetica')
        .fillColor('gray')
        .text('This is an automated receipt generated by the Inventory Management System.', {
          align: 'center',
        })
        .text('Office of the Registrar — High Court of Kenya', { align: 'center' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};

/**
 * Send store request receipt email with PDF attachment
 */
export const sendStoreRequestReceiptEmail = async (
  request: StoreRequest,
  requester: User,
  issuer: User
) => {
  const pdfBuffer = await generateStoreRequestPDF(request, requester, issuer);

  const subject = `Store Issue Receipt - ${request.item_name}`;

  const html = `
    <!DOCTYPE html>
    <html>
      <head><meta charset="UTF-8" /></head>
      <body style="font-family: Arial, sans-serif; color: #333;">
        <h2 style="color: #1E4620;">Store Issue Receipt</h2>
        <p><strong>Item:</strong> ${request.item_name}</p>
        <p><strong>Quantity:</strong> ${request.quantity} ${request.unit}</p>
        <p><strong>Issued To:</strong> ${requester.full_name}</p>
        <p><strong>Issued By:</strong> ${issuer.full_name}</p>
        <p><strong>Date Issued:</strong> ${new Date(request.issued_at!).toLocaleString()}</p>
        <p><strong>Status:</strong> ${request.status}</p>
        <p style="margin-top: 20px;">Please find the detailed receipt attached.</p>
        <hr />
        <p style="font-size: 12px; color: #888;">
          This is an automated message from the Judiciary Inventory Management System.
        </p>
      </body>
    </html>
  `;

  // Send to both requester and issuer
  const recipients = [requester.email, issuer.email];

  for (const email of recipients) {
    await sendMail({
      to: email,
      subject,
      html,
      attachments: [
        {
          content: pdfBuffer.toString('base64'),
          filename: `store_receipt_${request.id.slice(0, 8)}.pdf`,
          type: 'application/pdf',
          disposition: 'attachment',
        },
      ],
    });
  }
};