// scripts/landStatusSeeder.ts

import { pool } from "./config/db";

// Helper to clean text
const cleanText = (text: string | null | undefined): string | null => {
  if (!text) return null;
  return text.replace(/\s+/g, ' ').trim();
};

// Helper to handle empty/placeholder values
const cleanValue = (value: any): string | null => {
  if (!value || value === '' || value === '§' || value === 'UKNOWN' || value === 'N/A') {
    return null;
  }
  return cleanText(String(value));
};

// Land status seed data from Excel - Mapped exactly as per your table
const landStatusData = [
    // NAKURU - Naivasha New Site (Row 119)
  {
    county: 'NAKURU',
    file_ref: '32C2',
    property: 'Naivasha New Site',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // NAKURU - Naivasha Residence 6 (Row 120)
  {
    county: 'NAKURU',
    file_ref: '32C3',
    property: 'Naivasha Residence 6',
    title_percil_number: 'Milimani Naivasha',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // NAKURU - Naivasha Residence 11 (Row 121)
  {
    county: 'NAKURU',
    file_ref: '32C4',
    property: 'Naivasha Residence 11',
    title_percil_number: 'Milimani Naivasha',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'Unoccupied',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // NAKURU - Proposed Gilgil Law Courts (Row 122)
  {
    county: 'NAKURU',
    file_ref: '32C5',
    property: 'Proposed Gilgil Law Courts',
    title_percil_number: null,
    acreage: null,
    location: 'Gilgil Town',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Proposed for Gilgil Law Courts',
    ownership_status: 'County Government of Nakuru',
    possessions: 'UNKNOWN',
    fencing: 'not known',
    disputes: 'No disputes',
    recommendation: 'Enagege County Government to prepare PDP',
  },
  // NAROK - Narok New Site (Row 123)
  {
    county: 'NAROK',
    file_ref: '33A2',
    property: 'Narok New Site',
    title_percil_number: 'Plot No.470 (Survey No. 3740)',
    acreage: null,
    location: 'Narok Town',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Narok High Court',
    ownership_status: null,
    possessions: 'Unoccupied',
    fencing: 'Temporary Fence',
    disputes: 'No disputes',
    recommendation: 'Engage County Government for purposes of obtaining ownership documents',
  },
  // NAROK - Residence (Row 124)
  {
    county: 'NAROK',
    file_ref: '33A3',
    property: 'Narok - Residence',
    title_percil_number: 'Narok township/077',
    acreage: '2.019Ha',
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Judicary Staff Residence',
    ownership_status: null,
    possessions: 'Unoccupied',
    fencing: 'Not Fenced',
    disputes: 'No disputes',
    recommendation: 'Engage County Government for purposes of obtaining ownership documents',
  },
  // NAROK - Lolgorian New Site (Row 125)
  {
    county: 'NAROK',
    file_ref: '33A4',
    property: 'Narok Lolgorian New Site',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // NAROK - Murkan Dikkir New Site (Row 126)
  {
    county: 'NAROK',
    file_ref: '33A5',
    property: 'Narok Murkan Dikkir New Site',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // KAJIADO - Proposed Mashuuru Law Courts (Row 127)
  {
    county: 'KAJIADO',
    file_ref: '34A6',
    property: 'Kajiado - Proposed Mashuuru Law Courts',
    title_percil_number: 'Plot No. B156',
    acreage: '0.2333Ha',
    location: 'Mashuru Township',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Mashuru Law Courts',
    ownership_status: 'Allotment',
    possessions: 'Unoccupied',
    fencing: 'Not Fenced',
    disputes: 'No dispute',
    recommendation: 'Engage NLC',
  },
  // KAJIADO - Proposed Namanga Law Courts (Row 128)
  {
    county: 'KAJIADO',
    file_ref: '34A7',
    property: 'Kajiado - Proposed Namanga Law Courts',
    title_percil_number: 'Plot No. E215',
    acreage: '0.93Ha',
    location: 'Namanga Township',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Namanga Law Courts',
    ownership_status: 'Allotment',
    possessions: 'Unoccupied',
    fencing: 'Not Fenced',
    disputes: 'Partly grabbed',
    recommendation: 'Engage NLC',
  },
  // KAJIADO - Proposed Kisamis Law Courts (Row 129)
  {
    county: 'KAJIADO',
    file_ref: '34A8',
    property: 'Kajiado - Proposed Kisamis Law Courts',
    title_percil_number: null,
    acreage: '0.6285Ha',
    location: 'Kisamis Township',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Residence',
    ownership_status: 'Allotment',
    possessions: 'Unoccupied',
    fencing: 'Not Fenced',
    disputes: 'No dispute',
    recommendation: 'Engage NLC',
  },
  // KAJIADO - Proposed Kisamis Residence (Row 130)
  {
    county: 'KAJIADO',
    file_ref: '34A9',
    property: 'Kajiado - Proposed Kisamis Residence',
    title_percil_number: null,
    acreage: '0.1511Ha',
    location: 'Kisamis Township',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Kisamis Law Courts',
    ownership_status: 'Allotment',
    possessions: 'Unoccupied',
    fencing: 'Not Fenced',
    disputes: 'No dispute',
    recommendation: 'Engage NLC',
  },
  // KAJIADO - Loitoktok Law Courts (Row 131)
  {
    county: 'KAJIADO',
    file_ref: '34B',
    property: 'Loitoktok Law Courts',
    title_percil_number: 'Plot No. B196',
    acreage: '0.275Ha',
    location: 'Loitoktok Township',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Loitoktok Law Courts',
    ownership_status: 'Allotment',
    possessions: 'Occupied',
    fencing: 'Partly fenced',
    disputes: 'No dispute',
    recommendation: 'Engage NLC',
  },
  // KAJIADO - Ngong Law Courts (Row 132)
  {
    county: 'KAJIADO',
    file_ref: '34C1',
    property: 'Ngong Law Courts',
    title_percil_number: 'Plot No. A1',
    acreage: '0.272 Ha',
    location: 'Ngong Township',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Construction of Permanent Court building',
    ownership_status: 'Allottment',
    possessions: 'Occupied',
    fencing: 'Fenced',
    disputes: 'No dispute',
    recommendation: 'Engage NLC',
  },
  // KAJIADO - Ngong New Site (Row 133)
  {
    county: 'KAJIADO',
    file_ref: '34C2',
    property: 'Ngong – New Site',
    title_percil_number: 'Plot No. A058',
    acreage: '0.177Ha',
    location: 'Ngong Township',
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'Unoccupied',
    fencing: 'Not Fenced',
    disputes: 'No dispute',
    recommendation: 'Engage NLC',
  },
  // KERICHO - Sosiot New Site (Row 134)
  {
    county: 'KERICHO',
    file_ref: '35A2',
    property: 'Kericho – Sosiot New Site',
    title_percil_number: 'Not available',
    acreage: '0.27Ha',
    location: 'Chepkemel (Soin/Sigowet)',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Law Courts',
    ownership_status: 'No documentation',
    possessions: 'Unoccupied',
    fencing: 'Not Fenced',
    disputes: 'No dispute',
    recommendation: 'HoS to follow up on the documentation',
  },
  // KERICHO - Kipkelion New Site (Row 135)
  {
    county: 'KERICHO',
    file_ref: '35A3',
    property: 'Kericho – Kipkelion New Site',
    title_percil_number: 'PDP NO. LAPP/R45/16/01',
    acreage: '0.3750Ha',
    location: 'Kipkelion Town',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Law Courts',
    ownership_status: 'No documentation',
    possessions: 'Unoccupied',
    fencing: 'Not Fenced',
    disputes: 'No dispute',
    recommendation: 'HoS to follow up on the documentation',
  },
  // BOMET - Bomet New Site (Row 136)
  {
    county: 'BOMET',
    file_ref: '36A2',
    property: 'Bomet New Site',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // BOMET - Konoin Proposed (Row 137)
  {
    county: 'BOMET',
    file_ref: null,
    property: 'Bomet - Konoin Proposed',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // BOMET - Small Claims Court (Row 138)
  {
    county: 'BOMET',
    file_ref: null,
    property: 'Bomet Small Claims Court',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: 'Donated by County Government',
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // KAKAMEGA - Staff Quarters (Row 139)
  {
    county: 'KAKAMEGA',
    file_ref: '37A2',
    property: 'Kakamega Staff Quarters',
    title_percil_number: 'KAKAMEGA/MUNICIPALITY/BLOCK IV/730',
    acreage: '1.02 Ha',
    location: 'Kakamega Township',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Residence',
    ownership_status: 'PDP',
    possessions: 'Unoccupied',
    fencing: 'Not Fenced',
    disputes: 'No dispute',
    recommendation: 'Engage NLC',
  },
  // KAKAMEGA - Khwisero Mobile Court (Row 140)
  {
    county: 'KAKAMEGA',
    file_ref: '37C3',
    property: 'Khwisero Mobile Court',
    title_percil_number: 'KISA/WAMBULISHE/1313',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // KAKAMEGA - Butali Law Courts (Row 141)
  {
    county: 'KAKAMEGA',
    file_ref: '37D',
    property: 'Butali Law Courts',
    title_percil_number: 'Plot No. 91',
    acreage: '0.7Ha',
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // VIHIGA - Proposed Mwilonje (Row 142)
  {
    county: 'VIHIGA',
    file_ref: null,
    property: 'Vihiga – Proposed Mwilonje',
    title_percil_number: null,
    acreage: '1.2141 ha',
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // VIHIGA - Esibuye New Site (Row 143)
  {
    county: 'VIHIGA',
    file_ref: '38A2',
    property: 'Vihiga - Esibuye New Site',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // VIHIGA - New Site (Row 144)
  {
    county: 'VIHIGA',
    file_ref: '38A3',
    property: 'Vihiga - New Site',
    title_percil_number: 'South Maragoli/Buyonga/2875',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // VIHIGA - Emuhaya Proposed Court (Row 145)
  {
    county: 'VIHIGA',
    file_ref: null,
    property: 'Vihiga - Emuhaya Proposed Court',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // VIHIGA - Majengo Residence (Row 146)
  {
    county: 'VIHIGA',
    file_ref: null,
    property: 'Vihiga – Majengo Residence',
    title_percil_number: null,
    acreage: '0.1440 ha.',
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // VIHIGA - Mbale Children Court (Row 147)
  {
    county: 'VIHIGA',
    file_ref: null,
    property: 'Vihiga – Mbale Children Court',
    title_percil_number: 'W/VHG/339/2009/01',
    acreage: '0.4383HA',
    location: 'MBALE',
    status: 'UNPROCESSED LAND WITH DISPUTES',
    current_intended_use: null,
    ownership_status: 'PDP',
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: 'Dispute with the Police & Prisons Dept.',
    recommendation: null,
  },
  // VIHIGA - Mbale Residence (Row 148)
  {
    county: 'VIHIGA',
    file_ref: null,
    property: 'Vihiga – Mbale Residence',
    title_percil_number: 'W/VHG/339/2009/01',
    acreage: '0.35HA',
    location: null,
    status: 'UNPROCESSED LAND WITH DISPUTES',
    current_intended_use: null,
    ownership_status: 'PDP',
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: 'Dispute with the Police & Prisons',
    recommendation: null,
  },
  // BUNGOMA - Bungoma Law Courts (Row 149)
  {
    county: 'BUNGOMA',
    file_ref: '39A1',
    property: 'Bungoma Law Courts',
    title_percil_number: 'PDP BUN/KAND/2016/02',
    acreage: '0.44 ha',
    location: 'Bungoma Town',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Bungoma Law Courts',
    ownership_status: 'PDP',
    possessions: 'Occupied',
    fencing: null,
    disputes: null,
    recommendation: 'Engage County Government for approval of PDP',
  },
  // BUNGOMA - Kabuchai Old Court (Row 150)
  {
    county: 'BUNGOMA',
    file_ref: null,
    property: 'Kabuchai Old Court',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // BUNGOMA - Musikoma Proposed Court (Row 151)
  {
    county: 'BUNGOMA',
    file_ref: null,
    property: 'Musikoma Proposed Court',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // BUNGOMA - Kimilili Law Courts (Row 152)
  {
    county: 'BUNGOMA',
    file_ref: '39C1',
    property: 'Kimilili Law Courts',
    title_percil_number: 'W.65.2018.01',
    acreage: '0.8077 Ha',
    location: 'Kimilili',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Kimilili Law Courts',
    ownership_status: 'Draft PDP',
    possessions: 'Occupied',
    fencing: 'Fenced',
    disputes: 'No dispute',
    recommendation: 'Engage County Government',
  },
  // BUNGOMA - Kimilili Residence (Row 153)
  {
    county: 'BUNGOMA',
    file_ref: '39C3',
    property: 'Kimilili Residence',
    title_percil_number: '1.HOUSE NO. KIM/L&J/1/5 2.HOUSE NO. KIM/L&J/1/4A 3.HOUSE NO. KIM/L&J/1/4B 4.HOUSE NO. KIM/L&J/MG/1/6',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // BUNGOMA - Sirisia Law Courts (Row 154)
  {
    county: 'BUNGOMA',
    file_ref: '39D2',
    property: 'Sirisia Law Courts',
    title_percil_number: 'PLOT NO. 71',
    acreage: null,
    location: 'Sirisia Town',
    status: 'UNPROCESSED LAND WITH DISPUTES',
    current_intended_use: 'Law Courts',
    ownership_status: 'PDP',
    possessions: 'Encroached',
    fencing: 'Fenced',
    disputes: 'Dispute with a private developer',
    recommendation: 'Engage NLC',
  },
  // BUSIA - Busia Law Courts (Row 155)
  {
    county: 'BUSIA',
    file_ref: '40A1',
    property: 'Busia Law Courts',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // BUSIA - Nambale Old Colonial Court (Row 156)
  {
    county: 'BUSIA',
    file_ref: '40A3',
    property: 'Busia - Nambale Old Colonial Court',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // BUSIA - Butula New Site (Row 157)
  {
    county: 'BUSIA',
    file_ref: '40A4',
    property: 'Busia – Butula New Site',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // SIAYA - Siaya Law Courts (Row 158)
  {
    county: 'SIAYA',
    file_ref: '41A1',
    property: 'Siaya Law Courts',
    title_percil_number: 'SYA/32/2012/05',
    acreage: '0.1531Ha',
    location: 'Siaya Town',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'SIAYA Law Courts',
    ownership_status: 'PDP',
    possessions: 'Occupied',
    fencing: null,
    disputes: null,
    recommendation: 'Engage NLC for issuance of Allotment Letter',
  },
  // SIAYA - Siaya Residence (Row 159)
  {
    county: 'SIAYA',
    file_ref: '41A2',
    property: 'Siaya Residence',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // SIAYA - Bondo Law Courts (Row 160)
  {
    county: 'SIAYA',
    file_ref: '41B1',
    property: 'Bondo Law Courts',
    title_percil_number: 'SYA 340/02/3',
    acreage: '1.0610Ha',
    location: 'Bondo Town',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'BONDO Law Courts',
    ownership_status: 'PDP',
    possessions: 'Occupied',
    fencing: 'Fenced',
    disputes: 'No dispute',
    recommendation: 'Engage NLC for issuance of Allotment Letter',
  },
  // SIAYA - Usigu New Site (Row 161)
  {
    county: 'SIAYA',
    file_ref: '41B2',
    property: 'Bondo – Usigu New Site',
    title_percil_number: 'Siaya/usigu/295',
    acreage: '2 Acres',
    location: 'Usigu Town',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Proposed Usigu Law Courts',
    ownership_status: null,
    possessions: 'Occupied',
    fencing: null,
    disputes: 'No dispute',
    recommendation: null,
  },
  // SIAYA - Ukwala Residence (Row 162)
  {
    county: 'SIAYA',
    file_ref: '41C2',
    property: 'Ukwala Residence',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Unit allocated to the Judiciary by the county Government',
    ownership_status: null,
    possessions: 'Occupied',
    fencing: null,
    disputes: null,
    recommendation: 'Engage county government for preparation of PDP',
  },
  // SIAYA - Ugunja New Site (Row 163)
  {
    county: 'SIAYA',
    file_ref: '41C3',
    property: 'Ukwala – Ugunja New Site',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // SIAYA - Yala Law Courts (Row 164)
  {
    county: 'SIAYA',
    file_ref: '41E',
    property: 'Yala Law Courts',
    title_percil_number: null,
    acreage: null,
    location: 'Yala Town',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Proposed Yala Law courts',
    ownership_status: null,
    possessions: 'Occupied',
    fencing: 'Fenced',
    disputes: 'No dispute',
    recommendation: null,
  },
  // KISUMU - Kisumu Judge Residence (Row 165)
  {
    county: 'KISUMU',
    file_ref: '42A2',
    property: 'Kisumu Judge Residence',
    title_percil_number: 'KISUMU/HOUSE/HG/44',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // KISUMU - Kisumu CM Residence (Row 166)
  {
    county: 'KISUMU',
    file_ref: '42A3',
    property: 'Kisumu CM Residence',
    title_percil_number: 'KISUMU/MILIMANI/14',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // KISUMU - Winam Law Courts (Row 167)
  {
    county: 'KISUMU',
    file_ref: '42B',
    property: 'Winam Law Courts',
    title_percil_number: 'Parcel/Block 5/592',
    acreage: '0.28Ha',
    location: 'Kisumu Central',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Winam Law Courts',
    ownership_status: 'PDP',
    possessions: 'Occupied',
    fencing: null,
    disputes: 'No dispute',
    recommendation: 'Engage NLC for issuance of Allotment Letter',
  },
  // KISUMU - Maseno Residence (Row 168)
  {
    county: 'KISUMU',
    file_ref: '42C2',
    property: 'Maseno Residence',
    title_percil_number: 'Maseno/HG/1 Maseno/HG/10',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // KISUMU - Nyando Law Courts (Row 169)
  {
    county: 'KISUMU',
    file_ref: '42D1',
    property: 'Nyando Law Courts',
    title_percil_number: 'Nyando Plot No. 1844 Kakola',
    acreage: '1.212 Ha',
    location: 'Nyando Town',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Nyando Law Courts',
    ownership_status: 'Adjudication Section',
    possessions: 'Occupied',
    fencing: 'Fenced',
    disputes: 'No dispute',
    recommendation: 'Engage Director of Adjudiciation and Settlement',
  },
  // KISUMU - Proposed Nyakach / Sondu Miriu Law Courts (Row 170)
  {
    county: 'KISUMU',
    file_ref: '42D2',
    property: 'Nyando - Proposed Nyakach / Sondu Miriu Law Courts',
    title_percil_number: 'KAMNWA/KEYO OGORO/23',
    acreage: '0.889 Ha',
    location: 'Nyakach Town',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Law Courts',
    ownership_status: 'Allocated through Adjudiciation',
    possessions: 'Unoccupied',
    fencing: 'Not Fenced',
    disputes: 'No dispute',
    recommendation: 'Engage Director of Adjudiciation and Settlement',
  },
  // KISUMU - Tamu Old Court (Row 171)
  {
    county: 'KISUMU',
    file_ref: '42E',
    property: 'Tamu Old Court',
    title_percil_number: 'Tamu Township LR/10950/155',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // KISUMU - Kombewa Law Courts (Row 172)
  {
    county: 'KISUMU',
    file_ref: '42F',
    property: 'Kombewa Law Courts',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // HOMABAY - Oyugis Kosele Old Court (Row 173)
  {
    county: 'HOMABAY',
    file_ref: '43A',
    property: 'Oyugis – Kosele Old Court',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // HOMABAY - Oyugis New Site (Row 174)
  {
    county: 'HOMABAY',
    file_ref: '43B',
    property: 'Oyugis New Site',
    title_percil_number: 'Central Karachuonyo/Konyango/2515',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // HOMABAY - HOMA BAY ELC COURT (Row 175)
  {
    county: 'HOMABAY',
    file_ref: '43F',
    property: 'HOMA BAY ELC COURT',
    title_percil_number: 'HOMABAY MUNICIPALITY BLOCK 1/104',
    acreage: null,
    location: 'HOMABAY TOWN, OPP COUNTY ASSEMBLY',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'ELC COURT',
    ownership_status: 'OWNED BY NATIONAL GOVERNMENT',
    possessions: 'Occupied',
    fencing: 'NOT FENCED',
    disputes: 'No dispute',
    recommendation: null,
  },
  // HOMABAY - HOMA BAY MAGISTRATE COURTS (Row 176)
  {
    county: 'HOMABAY',
    file_ref: '43G',
    property: 'HOMA BAYMAGISTRATE COURTS',
    title_percil_number: 'HOMABAY MUNICIPALITY BLOCK 1/104',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: 'OWNED BY NATIONAL GOVERNMENT',
    possessions: 'Occupied',
    fencing: 'FENCED WITH CHAIN LINK',
    disputes: null,
    recommendation: null,
  },
  // MIGORI - Mabera New Site (Row 177)
  {
    county: 'MIGORI',
    file_ref: '44A3',
    property: 'Migori – Mabera New Site',
    title_percil_number: 'Kadem/Macalder/498',
    acreage: '0.404Ha',
    location: 'Macalder Township',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Macalder Law Courts',
    ownership_status: null,
    possessions: 'Unoccupied',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // MIGORI - Rongo Residence (Row 178)
  {
    county: 'MIGORI',
    file_ref: '44B2',
    property: 'Rongo Residence',
    title_percil_number: '5 Houses',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // MIGORI - Kehancha Kegonga New Site (Row 179)
  {
    county: 'MIGORI',
    file_ref: '44C2',
    property: 'Kehancha Kegonga New Site',
    title_percil_number: 'Bugembe/Mabera/79',
    acreage: '4.2Ha',
    location: 'Mabera',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Law Courts',
    ownership_status: null,
    possessions: 'Unoccupied',
    fencing: 'Not Fenced',
    disputes: 'No dispute',
    recommendation: null,
  },
  // KISII - Kisii New Site (Row 180)
  {
    county: 'KISII',
    file_ref: '45A3',
    property: 'Kisii New Site',
    title_percil_number: 'Opposite Kisii High School',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // KISII - Etago Law Courts (Row 181)
  {
    county: 'KISII',
    file_ref: '45C',
    property: 'Etago Law Courts',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // NYAMIRA - Borabu New Site (Row 182)
  {
    county: 'NYAMIRA',
    file_ref: '46A3',
    property: 'Nyamira – Borabu New Site',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // NYAMIRA - Keroka Residence (Row 183)
  {
    county: 'NYAMIRA',
    file_ref: '46B2',
    property: 'Keroka Residence',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // NYAMIRA - Manga (Row 184)
  {
    county: 'NYAMIRA',
    file_ref: null,
    property: 'Manga',
    title_percil_number: 'CENTRAL KITUTU/MWABOSIRE/1236',
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: null,
    recommendation: null,
  },
  // NAIROBI - Supreme Court (Row 185)
  {
    county: 'NAIROBI',
    file_ref: '47A',
    property: 'Supreme Court',
    title_percil_number: null,
    acreage: null,
    location: 'Nairobi',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Supreme Court of Kenya & Administrative Offices',
    ownership_status: null,
    possessions: 'Occupied',
    fencing: 'Fenced',
    disputes: null,
    recommendation: null,
  },
  // NAIROBI - Milimani Commercial (Row 186)
  {
    county: 'NAIROBI',
    file_ref: '47D',
    property: 'Milimani Commercial',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Milimani Commercial Court',
    ownership_status: null,
    possessions: 'Occupied',
    fencing: 'Fenced',
    disputes: null,
    recommendation: null,
  },
  // NAIROBI - COA Land (Row 187)
  {
    county: 'NAIROBI',
    file_ref: '47E',
    property: 'COA Land',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: 'EACC filed case at ELC Nairobi to revoke title issued to Swanya Ltd',
    recommendation: null,
  },
  // NAIROBI - JKIA Law Courts (Row 188)
  {
    county: 'NAIROBI',
    file_ref: '47I',
    property: 'JKIA Law Courts',
    title_percil_number: 'Land owned by KAA',
    acreage: 'N/A',
    location: 'JKIA',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Law Courts',
    ownership_status: 'N/A',
    possessions: 'Occupied',
    fencing: null,
    disputes: 'N/A',
    recommendation: 'Engage PS, Ministry of Lands for purposes of obtaining ownership documents',
  },
  // NAIROBI - Kahawa Law Courts (Row 189)
  {
    county: 'NAIROBI',
    file_ref: '47J',
    property: 'Kahawa Law Courts',
    title_percil_number: 'Not Processed',
    acreage: '1.495 Ha for Magistrates court & 1.414Ha for proposed High Court',
    location: 'Kahawa, Kamiti Road',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Law Courts',
    ownership_status: null,
    possessions: 'Occupied',
    fencing: 'Fenced',
    disputes: 'No dispute',
    recommendation: 'HoS in collaboration with OCRJ to pursue subdivision and allocation',
  },
  // NAIROBI - Dagoretti Law Courts (Row 190)
  {
    county: 'NAIROBI',
    file_ref: '47K',
    property: 'Dagoretti Law Courts',
    title_percil_number: 'N/A',
    acreage: 'N/A',
    location: 'Dagorreti',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Law Courts',
    ownership_status: null,
    possessions: 'Occupied',
    fencing: null,
    disputes: null,
    recommendation: 'Engage County Government for issuance of PDP and Allotment Letter',
  },
  // NAIROBI - Dennis Pritt Residence (Row 191)
  {
    county: 'NAIROBI',
    file_ref: '47M',
    property: 'Dennis Pritt Residence',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: 'EACC filed case at ELC Nairobi to revoke title issued to private company',
    recommendation: null,
  },
  // NAIROBI - Judge Omange Residence (Row 192)
  {
    county: 'NAIROBI',
    file_ref: '47N',
    property: 'Judge Omange Residence',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'Occupied',
    fencing: 'Fenced',
    disputes: 'EACC filed case at ELC Nairobi to revoke title issued to private company',
    recommendation: null,
  },
  // NAIROBI - Hurlingham Property (Row 193)
  {
    county: 'NAIROBI',
    file_ref: '47O',
    property: 'Hurlingham Property',
    title_percil_number: null,
    acreage: null,
    location: null,
    status: 'UNPROCESSED LAND',
    current_intended_use: null,
    ownership_status: null,
    possessions: 'UNKNOWN',
    fencing: null,
    disputes: 'Dec 2024 – Occupation by Hon Maureen Shimenga § Fencing completed in Feb 2025',
    recommendation: null,
  },
  // NAIROBI - Kasarani Small Claims Court (Row 194)
  {
    county: 'NAIROBI',
    file_ref: '47P',
    property: 'Kasarani Small Claims Court',
    title_percil_number: 'N/A',
    acreage: 'N/A',
    location: 'Kasarani',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Law Courts',
    ownership_status: null,
    possessions: 'Unoccupied',
    fencing: 'Not Fenced',
    disputes: null,
    recommendation: 'Engage County Government for issuance of PDP and Allotment Letter',
  },
    // NAIROBI - Mihango Small Claims Court (Row 195)
  {
    county: 'NAIROBI',
    file_ref: '47Q',
    property: 'Mihango Small Claims Court',
    title_percil_number: 'N/A',
    acreage: 'N/A',
    location: 'Mihango',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Law Courts',
    ownership_status: null,
    possessions: 'Unoccupied',
    fencing: 'Fenced',
    disputes: null,
    recommendation: 'Engage County Government for issuance of PDP and Allotment Letter',
  },
  // NAIROBI - Huruma Small Claims Court (Row 196)
  {
    county: 'NAIROBI',
    file_ref: '47S',
    property: 'Huruma Small Claims Court',
    title_percil_number: 'N/A',
    acreage: 'N/A',
    location: 'Huruma',
    status: 'UNPROCESSED LAND',
    current_intended_use: 'Law Courts',
    ownership_status: null,
    possessions: 'Unoccupied',
    fencing: 'Fenced',
    disputes: null,
    recommendation: 'Engage County Government for issuance of PDP and Allotment Letter',
  },
];

const seedLandStatus = async () => {
  console.log('🌱 Starting Land Status seed...');
  console.log('=====================================\n');
  console.log(`📊 Total records to process: ${landStatusData.length}\n`);

  let inserted = 0;
  let failed = 0;
  let skipped = 0;

  for (const data of landStatusData) {
    try {
      // Check if record already exists using county and property combination
      // since file_ref can be null
      let existing;
      if (data.file_ref) {
        existing = await pool.query(
          `SELECT id FROM land_status WHERE county = $1 AND file_ref = $2`,
          [data.county, data.file_ref]
        );
      } else {
        existing = await pool.query(
          `SELECT id FROM land_status WHERE county = $1 AND property = $2`,
          [data.county, data.property]
        );
      }

      if (existing.rows.length > 0) {
        console.log(`⏭️ Skipping existing: ${data.county} - ${data.file_ref || data.property}`);
        skipped++;
        continue;
      }

      console.log(`📝 Processing: ${data.county} - ${data.file_ref || data.property}`);
      console.log(`   Property: ${data.property || 'N/A'}`);
      console.log(`   Status: ${data.status}`);

      const result = await pool.query(
        `INSERT INTO land_status (
          county, file_ref, property, title_percil_number, acreage,
          location, status, current_intended_use, ownership_status,
          possessions, fencing, disputes, recommendation
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
        RETURNING id`,
        [
          data.county,
          data.file_ref,
          cleanValue(data.property),
          cleanValue(data.title_percil_number),
          data.acreage,
          cleanValue(data.location),
          data.status,
          cleanValue(data.current_intended_use),
          cleanValue(data.ownership_status),
          cleanValue(data.possessions),
          cleanValue(data.fencing),
          cleanValue(data.disputes),
          cleanValue(data.recommendation),
        ]
      );

      console.log(`   ✅ Inserted - ID: ${result.rows[0].id}\n`);
      inserted++;
    } catch (error) {
      console.error(`   ❌ Failed to insert ${data.county} - ${data.file_ref || data.property}:`, error);
      failed++;
    }
  }

  console.log('=====================================');
  console.log('📊 Seeding Summary:');
  console.log(`   ✅ Inserted: ${inserted} records`);
  console.log(`   ⏭️ Skipped: ${skipped} records`);
  console.log(`   ❌ Failed: ${failed} records`);
  console.log(`   📝 Total processed: ${landStatusData.length} records`);
  
  console.log('\n✨ Land Status seeding completed!');
};

// Run seeder if called directly
if (require.main === module) {
  seedLandStatus()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error('Fatal error during seeding:', error);
      process.exit(1);
    });
}

export { seedLandStatus };